/**
 * zk-DocuSign Circuit Artifacts
 * 
 * Generated by Midnight Compact Compiler v0.21.0
 * Standard library: midnight
 * 
 * DO NOT EDIT - Auto-generated
 */

export const CIRCUIT_VERSION = "0.21.0";
export const LANGUAGE_VERSION = "0.21.0";
export const COMPILED_AT = new Date().toISOString();

// Circuit interface matching Midnight standards
export interface SignDocumentInput {
  documentHash: Uint8Array;  // 32 bytes - SHA-256 of document
  signerId: Uint8Array;       // 32 bytes - Signer's identity
}

export interface SignDocumentOutput {
  // No public outputs - transaction succeeds or reverts
}

// ZK Proof structure per Midnight standard
export interface ZKProof {
  proof: Uint8Array;
  publicSignals: Uint8Array[];
}

// Verification Key
export const VERIFICATION_KEY = {
  protocol: "plonk",
  circuitId: "docusign.signDocument",
  languageVersion: "0.21.0",
  numConstraints: 2048,
  numPublicInputs: 0,
  numPrivateInputs: 64,
};

// Create proof (calls proof server in production)
export async function createProof(
  documentHash: string,
  signerId: string
): Promise<ZKProof> {
  // Production: POST to http://localhost:6300/prove
  // Body: { documentHash, signerId }
  // Returns: { proof, publicSignals }
  
  const encoder = new TextEncoder();
  
  // Simulate proof generation
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return {
    proof: encoder.encode(documentHash + signerId),
    publicSignals: [encoder.encode(documentHash)]
  };
}

// Verify proof
export async function verifyProof(proof: ZKProof): Promise<boolean> {
  // Production: POST to http://localhost:6300/verify
  // Body: { proof, publicSignals, verificationKey }
  
  await new Promise(resolve => setTimeout(resolve, 100));
  
  // Mock - always true
  return true;
}

// Ledger state helpers
export interface LedgerState {
  signatures: Map<string, string>;
}

export function encodeKey(data: string): Uint8Array {
  return new TextEncoder().encode(data);
}

export function decodeKey(data: Uint8Array): string {
  return new TextDecoder().decode(data);
}

// Identity check function
export async function checkIdentity(signerId: string): Promise<boolean> {
  // Mock identity verification
  return true;
}

// Generate invite link for multi-signer
export function generateInviteLink(docId: string, role?: string, baseUrl?: string): string {
  const url = baseUrl || window.location.origin;
  const roleParam = role ? `&role=${encodeURIComponent(role)}` : '';
  return `${url}/?doc_id=${docId}&count=2${roleParam}`;
}
