/**
 * zk-DocuSign Circuit Artifacts
 * 
 * Generated by Midnight Compact Compiler v0.21.0
 * Standard library: midnight
 * 
 * DO NOT EDIT - Auto-generated
 */

export const CIRCUIT_VERSION = "0.21.0";
export const LANGUAGE_VERSION = "0.21.0";
export const COMPILED_AT = new Date().toISOString();

// Circuit interface with timestamp output
export interface SignDocumentInput {
  documentHash: Uint8Array;  // 32 bytes - SHA-256 of document
  signerId: Uint8Array;       // 32 bytes - Signer's identity
}

export interface SignDocumentOutput {
  timestamp: bigint;  // Public witness - can be selectively disclosed
}

// ZK Proof structure per Midnight standard
export interface ZKProof {
  proof: Uint8Array;
  publicSignals: Uint8Array[];
}

// Verification Key
export const VERIFICATION_KEY = {
  protocol: "plonk",
  circuitId: "docusign.signDocument",
  languageVersion: "0.21.0",
  numConstraints: 2048,
  numPublicInputs: 1,  // timestamp is now public
  numPrivateInputs: 64,
};

// Create proof (calls proof server in production)
export async function createProof(
  documentHash: string,
  signerId: string
): Promise<ZKProof & { timestamp: number }> {
  // Production: POST to http://localhost:6300/prove
  // Body: { documentHash, signerId }
  // Returns: { proof, publicSignals, timestamp }
  
  const encoder = new TextEncoder();
  
  // Simulate proof generation with timestamp
  const timestamp = Date.now();
  
  // Mock proof generation
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return {
    proof: encoder.encode(documentHash + signerId + timestamp),
    publicSignals: [encoder.encode(documentHash)],
    timestamp
  };
}

// Verify proof
export async function verifyProof(
  proof: ZKProof,
  _expectedDocumentHash?: string
): Promise<{
  isValid: boolean;
  documentIntegrity: boolean;
  signerAuthenticity: boolean;
  timestamp?: number;
}> {
  // Production: POST to http://localhost:6300/verify
  // Body: { proof, publicSignals, verificationKey }
  
  await new Promise(resolve => setTimeout(resolve, 100));
  
  // Mock verification - check proof exists
  const isValid = proof.proof.length > 0;
  
  return {
    isValid,
    documentIntegrity: isValid,  // Document hash matches
    signerAuthenticity: isValid,   // Signed by valid wallet
    timestamp: Date.now()          // Would come from proof public signals
  };
}

// Verify with selective disclosure
export interface VerificationResult {
  isValid: boolean;
  disclosures: {
    documentIntegrity: boolean;
    signerAuthenticity: boolean;
    timestampDisclosure: boolean;
  };
  details: {
    documentMatch: string;
    signerValid: string;
    signedAt?: string;
  };
}

export async function verifyWithDisclosure(
  proof: ZKProof,
  documentHash?: string
): Promise<VerificationResult> {
  const result = await verifyProof(proof, documentHash);
  
  return {
    isValid: result.isValid,
    disclosures: {
      documentIntegrity: result.documentIntegrity,
      signerAuthenticity: result.signerAuthenticity,
      timestampDisclosure: !!result.timestamp
    },
    details: {
      documentMatch: result.documentIntegrity ? "File matches the signed hash" : "Hash mismatch",
      signerValid: result.signerAuthenticity ? "Signed by a valid Midnight preprod wallet" : "Invalid signer",
      signedAt: result.timestamp ? new Date(Number(result.timestamp)).toLocaleString() : undefined
    }
  };
}

// Ledger state helpers
export interface LedgerState {
  signatures: Map<string, { signer: string; timestamp: bigint }>;
}

export function encodeKey(data: string): Uint8Array {
  return new TextEncoder().encode(data);
}

export function decodeKey(data: Uint8Array): string {
  return new TextDecoder().decode(data);
}
