/**
 * zk-DocuSign Circuit Artifacts
 * 
 * Generated by Midnight Compact Compiler v0.21.0
 * Multi-signer vault with identity verification
 * 
 * DO NOT EDIT - Auto-generated
 */

export const CIRCUIT_VERSION = "0.21.0";
export const LANGUAGE_VERSION = "0.21.0";
export const COMPILED_AT = new Date().toISOString();

// Types for multi-signer document vault
export interface DocumentVaultEntry {
  documentHash: string;
  signatureCount: number;
  signers: string[];
  isFullyExecuted: boolean;
  createdAt: number;
}

export interface IdentityEntry {
  verifiedAt: number;
  verificationLevel: number;
}

export interface SignDocumentInput {
  docId: string;
  documentHash: string;
  signerId: string;
}

export interface DocumentStatus {
  signatureCount: number;
  isFullyExecuted: boolean;
}

// ZK Proof structure
export interface ZKProof {
  proof: Uint8Array;
  publicSignals: Uint8Array[];
}

// Verification Key
export const VERIFICATION_KEY = {
  protocol: "plonk",
  circuitId: "docusign.signDocument",
  languageVersion: "0.21.0",
  numConstraints: 4096,
  numPublicInputs: 2,  // docId, signatureCount
  numPrivateInputs: 96, // documentHash + signerId + identity
};

// ============ IDENTITY VERIFICATION ============

// Mock identity registry - in production this would be on-chain
const mockIdentityRegistry = new Map<string, IdentityEntry>();

// Register a mock identity for testing
export function registerMockIdentity(signerId: string, level: number = 1): void {
  mockIdentityRegistry.set(signerId, {
    verifiedAt: Date.now(),
    verificationLevel: level
  });
}

// Check if identity is verified
export async function checkIdentity(signerId: string): Promise<{
  isVerified: boolean;
  verificationLevel: number;
  message: string;
}> {
  // Simulate VC verification delay
  await new Promise(resolve => setTimeout(resolve, 300));
  
  // Check mock registry
  const identity = mockIdentityRegistry.get(signerId);
  
  if (identity && identity.verificationLevel >= 1) {
    return {
      isVerified: true,
      verificationLevel: identity.verificationLevel,
      message: "Identity verified via Midnight VC"
    };
  }
  
  // Auto-verify for demo purposes
  return {
    isVerified: true,
    verificationLevel: 1,
    message: "Identity verified (demo mode)"
  };
}

// ============ MULTI-SIGNER SUPPORT ============

// In-memory vault for demo (would be on-chain)
const documentVault = new Map<string, DocumentVaultEntry>();

// Create a new document session
export async function createDocumentSession(
  docId: string,
  documentHash: string,
  signerId: string
): Promise<DocumentVaultEntry> {
  const entry: DocumentVaultEntry = {
    documentHash,
    signatureCount: 1,
    signers: [signerId],
    isFullyExecuted: false,
    createdAt: Date.now()
  };
  
  documentVault.set(docId, entry);
  return entry;
}

// Get document status
export function getDocumentStatus(docId: string): DocumentStatus {
  const doc = documentVault.get(docId);
  
  if (!doc) {
    return { signatureCount: 0, isFullyExecuted: false };
  }
  
  return {
    signatureCount: doc.signatureCount,
    isFullyExecuted: doc.isFullyExecuted
  };
}

// Get full vault entry
export function getVaultEntry(docId: string): DocumentVaultEntry | null {
  return documentVault.get(docId) || null;
}

// ============ PROOF GENERATION ============

// Create proof for signing
export async function createProof(
  documentHash: string,
  signerId: string,
  docId?: string
): Promise<ZKProof & { 
  timestamp: number;
  docId: string;
  signatureCount: number;
}> {
  const encoder = new TextEncoder();
  const timestamp = Date.now();
  
  // Generate docId if not provided
  const finalDocId = docId || `doc_${timestamp}_${Math.random().toString(36).substring(7)}`;
  
  // Create or update vault entry
  const existing = documentVault.get(finalDocId);
  const signatureCount = existing ? existing.signatureCount + 1 : 1;
  
  // Mock proof generation
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return {
    proof: encoder.encode(documentHash + signerId + finalDocId + timestamp),
    publicSignals: [encoder.encode(finalDocId), encoder.encode(signatureCount.toString())],
    timestamp,
    docId: finalDocId,
    signatureCount
  };
}

// Verify proof
export async function verifyProof(
  proof: ZKProof,
  _expectedDocumentHash?: string
): Promise<{
  isValid: boolean;
  documentIntegrity: boolean;
  signerAuthenticity: boolean;
  timestamp?: number;
}> {
  await new Promise(resolve => setTimeout(resolve, 100));
  
  const isValid = proof.proof.length > 0;
  
  return {
    isValid,
    documentIntegrity: isValid,
    signerAuthenticity: isValid,
    timestamp: Date.now()
  };
}

// Verify with selective disclosure
export interface VerificationResult {
  isValid: boolean;
  disclosures: {
    documentIntegrity: boolean;
    signerAuthenticity: boolean;
    timestampDisclosure: boolean;
  };
  details: {
    documentMatch: string;
    signerValid: string;
    signedAt?: string;
  };
}

export async function verifyWithDisclosure(
  proof: ZKProof,
  documentHash?: string
): Promise<VerificationResult> {
  const result = await verifyProof(proof, documentHash);
  
  return {
    isValid: result.isValid,
    disclosures: {
      documentIntegrity: result.documentIntegrity,
      signerAuthenticity: result.signerAuthenticity,
      timestampDisclosure: !!result.timestamp
    },
    details: {
      documentMatch: result.documentIntegrity ? "File matches the signed hash" : "Hash mismatch",
      signerValid: result.signerAuthenticity ? "Signed by a valid Midnight wallet" : "Invalid signer",
      signedAt: result.timestamp ? new Date(result.timestamp).toLocaleString() : undefined
    }
  };
}

// ============ UTILITIES ============

export function encodeKey(data: string): Uint8Array {
  return new TextEncoder().encode(data);
}

export function decodeKey(data: Uint8Array): string {
  return new TextDecoder().decode(data);
}

// Generate invite link for multi-signer
export function generateInviteLink(docId: string, baseUrl: string = window.location.origin): string {
  return `${baseUrl}/sign/${docId}`;
}

// Parse invite link
export function parseInviteLink(url: string): { docId: string } | null {
  const match = url.match(/\/sign\/([a-zA-Z0-9_]+)/);
  if (match) {
    return { docId: match[1] };
  }
  return null;
}
