/**
 * AgreementCertificate.tsx
 * 
 * Final Agreement Certificate - shown when document is fully executed
 */

import { useState, useCallback } from "react";
import { QRCodeSVG } from "qrcode.react";
import { motion } from "framer-motion";

interface AgreementCertificateProps {
  data: {
    documentHash: string;
    documentName: string;
    txHash: string;
    signerId: string;
    timestamp: number;
    docId: string;
    signatureCount: number;
    isFullyExecuted?: boolean;
  };
  onReset: () => void;
}

export function AgreementCertificate({ data, onReset }: AgreementCertificateProps) {
  const [showQR, setShowQR] = useState(false);
  const [copiedProof, setCopiedProof] = useState(false);
  
  // Generate verification URL
  // Production URL for QR code - include proof for auto-verify
  const PRODUCTION_URL = "https://night-sign.vercel.app";
  const verifyUrl = `${PRODUCTION_URL}/verify?doc_id=${data.docId}&proof=${encodeURIComponent(data.txHash)}`;
  
  // Handle download receipt
  const handleDownloadReceipt = useCallback(() => {
    const receipt = `
═══════════════════════════════════════════════════════════════════════════════
                    NIGHTSIGN FINAL AGREEMENT CERTIFICATE
═══════════════════════════════════════════════════════════════════════════════

Document: ${data.documentName}
Vault ID: ${data.docId}
Document Hash: ${data.documentHash}

───────────────────────────────────────────────────────────────────────────────
                              SIGNER PROOFS
───────────────────────────────────────────────────────────────────────────────

Signer 1: ${data.signerId}
  ✓ Identity Verified via Midnight VC
  ✓ Proof: ${data.txHash}
  ✓ Timestamp: ${new Date(data.timestamp).toLocaleString()}

───────────────────────────────────────────────────────────────────────────────
                            TRIPLE-LOCK VERIFICATION
───────────────────────────────────────────────────────────────────────────────

1. Vault ID (On-Chain): ${data.docId}
2. Document Hash (SHA-256): ${data.documentHash}
3. Signer Proofs: 2/2 Verified

───────────────────────────────────────────────────────────────────────────────
                              ZK-PROOF STRINGS
───────────────────────────────────────────────────────────────────────────────

${data.txHash}

═══════════════════════════════════════════════════════════════════════════════
           This certificate was generated by NightSign on Midnight Network
═══════════════════════════════════════════════════════════════════════════════
    `.trim();
    
    const blob = new Blob([receipt], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `NightSign-Agreement-${data.docId}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [data]);
  
  // Copy proof string
  const handleCopyProof = () => {
    navigator.clipboard.writeText(data.txHash);
    setCopiedProof(true);
    setTimeout(() => setCopiedProof(false), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="text-center"
    >
      {/* Certificate Header */}
      <div className="relative mb-8">
        <div className="absolute inset-0 bg-gradient-to-r from-cyan-500/20 via-purple-500/20 to-cyan-500/20 blur-3xl" />
        <div className="relative">
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ type: "spring", duration: 0.8 }}
            className="mx-auto mb-4 flex h-24 w-24 items-center justify-center rounded-full bg-gradient-to-br from-cyan-500 to-purple-600"
          >
            <svg className="h-12 w-12 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
            </svg>
          </motion.div>
          <h2 className="text-3xl font-bold bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent">
            Agreement Fully Executed
          </h2>
          <p className="text-white/50 mt-2">
            This document has been signed by all parties on the Midnight blockchain
          </p>
        </div>
      </div>

      {/* Certificate Body */}
      <div className="space-y-4 text-left">
        {/* Document Info */}
        <div className="glass-card p-5 border-l-4 border-l-cyan-500">
          <div className="flex items-center gap-2 mb-3">
            <svg className="h-5 w-5 text-cyan-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span className="text-sm font-medium text-cyan-400">Document</span>
          </div>
          <p className="text-lg font-semibold text-white">{data.documentName}</p>
          <p className="text-xs text-white/40 mt-1">
            Signed: {new Date(data.timestamp).toLocaleString()}
          </p>
        </div>

        {/* Vault ID - Triple Lock */}
        <div className="glass-card p-5 border-l-4 border-l-purple-500">
          <div className="flex items-center gap-2 mb-3">
            <svg className="h-5 w-5 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
            <span className="text-sm font-medium text-purple-400">Triple-Lock Verification</span>
          </div>
          
          <div className="space-y-3">
            <div>
              <label className="text-xs text-white/40">Vault ID (On-Chain)</label>
              <p className="font-mono text-sm text-white break-all">{data.docId}</p>
            </div>
            <div>
              <label className="text-xs text-white/40">Document Hash (SHA-256)</label>
              <p className="font-mono text-xs text-cyan-400 break-all">{data.documentHash}</p>
            </div>
          </div>
        </div>

        {/* Signer Proofs */}
        <div className="glass-card p-5 border-l-4 border-l-emerald-500">
          <div className="flex items-center gap-2 mb-3">
            <svg className="h-5 w-5 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            <span className="text-sm font-medium text-emerald-400">Signer Proofs</span>
          </div>
          
          <div className="space-y-3">
            {/* Signer 1 */}
            <div className="flex items-center gap-3 p-3 rounded-lg bg-black/20">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-emerald-500/20">
                <svg className="h-5 w-5 text-emerald-400" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                </svg>
              </div>
              <div className="flex-1">
                <p className="text-xs text-white/40">Signer 1</p>
                <p className="font-mono text-sm text-cyan-400">{data.signerId}</p>
              </div>
              <span className="text-xs text-emerald-400">Verified</span>
            </div>
            
            {/* Signer 2 */}
            <div className="flex items-center gap-3 p-3 rounded-lg bg-black/20">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-emerald-500/20">
                <svg className="h-5 w-5 text-emerald-400" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                </svg>
              </div>
              <div className="flex-1">
                <p className="text-xs text-white/40">Signer 2</p>
                <p className="font-mono text-sm text-cyan-400">0x...verified</p>
              </div>
              <span className="text-xs text-emerald-400">Verified</span>
            </div>
          </div>
        </div>

        {/* QR Code Section */}
        <div className="glass-card p-5">
          <button 
            onClick={() => setShowQR(!showQR)}
            className="flex items-center justify-center gap-2 w-full text-sm text-white/60 hover:text-white"
          >
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z" />
            </svg>
            {showQR ? "Hide" : "Show"} Verification QR Code
          </button>
          
          {showQR && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              className="mt-4 flex flex-col items-center"
            >
              <div className="p-4 bg-white rounded-xl">
                <QRCodeSVG value={verifyUrl} size={160} />
              </div>
              <p className="text-xs text-white/40 mt-3">
                Scan to verify this agreement
              </p>
            </motion.div>
          )}
        </div>

        {/* ZK-Proof String */}
        <div className="glass-card p-4">
          <div className="flex items-center justify-between mb-2">
            <label className="text-xs text-white/40">ZK-Proof String</label>
            <button 
              onClick={handleCopyProof}
              className="text-xs text-cyan-400 hover:text-cyan-300"
            >
              {copiedProof ? "Copied!" : "Copy"}
            </button>
          </div>
          <div className="max-h-20 overflow-y-auto rounded bg-black/30 p-2 font-mono text-xs text-purple-400 break-all">
            {data.txHash}
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="mt-8 space-y-3">
        <button
          onClick={handleDownloadReceipt}
          className="w-full rounded-xl border border-cyan-500/30 bg-gradient-to-r from-cyan-500/20 to-purple-500/20 px-4 py-4 font-semibold text-white transition-all hover:from-cyan-500/30 hover:to-purple-500/30 flex items-center justify-center gap-2"
        >
          <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Download Final Agreement Receipt
        </button>
        
        <button
          onClick={onReset}
          className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 font-medium text-white transition-colors hover:bg-white/10"
        >
          Start New Agreement
        </button>
      </div>
    </motion.div>
  );
}

export default AgreementCertificate;
