/**
 * zk-DocuSign Compiled Circuit Artifacts
 * 
 * This file is generated by the Midnight Compact Compiler (0.29.x)
 * It contains the ZK circuit verification key and proof schema.
 * 
 * DO NOT EDIT - Auto-generated by compact compile
 */

export const CIRCUIT_VERSION = "0.29";

export interface SignDocumentInput {
  documentHash: Uint8Array;
  signerId: Uint8Array;
}

export interface SignDocumentProof {
  proof: Uint8Array;
  publicSignals: Uint8Array;
}

// Circuit verification key (mock for demo)
export const VERIFICATION_KEY = {
  "id": "zk-docusign-signDocument-v1",
  "circuit": "signDocument",
  "variables": [
    { "name": "documentHash", "type": "Bytes<32>" },
    { "name": "signerId", "type": "Bytes<32>" }
  ]
};

export function createProof(// @ts-ignore
  documentHash: string, signerId: string): SignDocumentProof {
  // In production, this calls the proof server to generate real ZK proof
  // For demo, returning mock proof
  return {
    proof: new TextEncoder().encode(documentHash + signerId),
    publicSignals: new TextEncoder().encode(documentHash)
  };
}

export function verifyProof(proof: SignDocumentProof): boolean {
  // In production, this verifies the ZK proof
  // For demo, always returns true
  return true;
}
