// Contract bindings - Compact v0.28.0 with circuit keyword
// In production, this would be generated by the Compact compiler

export interface ZKProof {
  proof: Uint8Array;
  publicSignals: string[];
}

export interface ContractParams {
  proofServerUrl?: string;
}

// Compact v0.28.0 circuit-based contract
export class DocumentSignerContract {
  constructor(
    public providers: any, 
    public params: ContractParams = {}
  ) {}
  
  // circuit keyword - direct ZK circuit invocation
  get circuits() {
    return {
      // sign_document circuit per Compact v0.28.0
      sign_document: async (docHash: string, options?: { role?: string }) => {
        console.log("Executing circuit sign_document with:", docHash, "role:", options?.role);
        
        // In production: POST to proof server for ZK proof generation
        if (this.params.proofServerUrl) {
          try {
            const response = await fetch(`${this.params.proofServerUrl}/prove`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                circuit: 'sign_document',
                documentHash: docHash,
                // Role is disclosed in the circuit (v0.28.0 standard)
                role: options?.role || 'Signer'
              })
            });
            if (response.ok) {
              return await response.json();
            }
          } catch (e) {
            console.warn('Proof server unavailable, using local generation');
          }
        }
        
        // Local proof generation (demo mode)
        const encoder = new TextEncoder();
        const role = options?.role || 'Signer';
        
        return {
          proof: encoder.encode(docHash + role),
          publicSignals: [docHash],
          // disclose() equivalent - role revealed on-chain
          metadata: { role, disclosed: true }
        };
      }
    };
  }
}

// ZK Proof creation function
export async function createProof(documentHash: string, signer: string, docId?: string, role?: string): Promise<ZKProof> {
  console.log("Creating ZK proof for:", documentHash, "signer:", signer, "role:", role);
  
  const encoder = new TextEncoder();
  
  // Simulate proof generation delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  return {
    proof: encoder.encode(documentHash + signer + (role || '')),
    publicSignals: [documentHash, docId || '']
  };
}
